### ISSUE TITLE
Compile time Exception in v0.3.1 for Array[String]

### ISSUE THREAD

**Issue by hrj** [lihaoyi/upickle-pprint#96]
### Input
```scala
sealed trait Field { }

case class ChoiceField(choices: Array[String]) extends Field
```

### Output

```
exception during macro expansion: 
[error] scala.ScalaReflectionException: value apply encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
[error] 	at scala.reflect.api.Symbols$SymbolApi$class.asMethod(Symbols.scala:228)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:84)
[error] 	at derive.Derive$$anonfun$getArgSyms$1.apply(Derive.scala:347)
[error] 	at derive.Derive$$anonfun$getArgSyms$1.apply(Derive.scala:342)
[error] 	at scala.util.Either$RightProjection.flatMap(Either.scala:522)
[error] 	at derive.Derive.getArgSyms(Derive.scala:342)
[error] 	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:121)
[error] 	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:170)
[error] 	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:149)
[error] 	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
[error] 	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error] 	at derive.Derive.derive$Derive$$rec$1(Derive.scala:149)
[error] 	at derive.Derive$$anonfun$5.apply(Derive.scala:128)
[error] 	at derive.Derive$$anonfun$5.apply(Derive.scala:128)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:327)
[error] 	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:128)
[error] 	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:170)
[error] 	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:149)
[error] 	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
[error] 	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error] 	at derive.Derive.derive$Derive$$rec$1(Derive.scala:149)
[error] 	at derive.Derive.deriveType(Derive.scala:183)
[error] 	at derive.Derive.derive(Derive.scala:58)
[error] 	at upickle.Macros$.macroRImpl(Macros.scala:125)
[error]       read[uni.ChoiceField]("")

```

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/upickle-pprint/commit/1a4510164bc3ddc58db982539734aa4fc2596dda
